### ISSUE TITLE
ticking crash

### ISSUE THREAD

**Issue by cajlo** [coderbot16/SimpleFlax#12]
I'm using custom modpack, everything was ok, but after ~2-3 weeks of playing I started to get this error

```
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=ayyge, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:201)
	at simpleflax.blocks.BlockFlax.isMaxAgeForReal(BlockFlax.java:65)
	at simpleflax.blocks.BlockFlax.canGrow(BlockFlax.java:131)
	at com.endertech.minecraft.mods.adpother.blocks.Pollutant.doBonemealEffect(Pollutant.java:877)
	at com.endertech.minecraft.mods.adpother.blocks.Carbon.affectBlockAt(Carbon.java:85)
	at com.endertech.minecraft.mods.adpother.blocks.GasEmission.affectUnderlyingBlock(GasEmission.java:212)
	at com.endertech.minecraft.mods.adpother.blocks.GasEmission.TickCentral_TrueRandomTick(GasEmission.java:665)
	at com.github.terminatornl.tickcentral.api.TickHub.trueRandomTick(TickHub.java:28)
	at com.github.terminatornl.laggoggles.Main.redirectRandomTick(Main.java:81)
	at com.endertech.minecraft.mods.adpother.blocks.GasEmission.randomTick(GasEmission.java)
	at net.minecraft.world.WorldServer.updateBlocks(WorldServer.java:476)
	at net.minecraft.world.WorldServer.tick(WorldServer.java:225)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:750)
```

Full crash report https://pastebin.com/77hqre0K

I can fix it only by removing mod from server, and helps for 2-3 days after get it back

**Comment by coderbot16** [comment]
Looked into it out of curiosity:

https://github.com/coderbot16/SimpleFlax/blob/master/src/main/java/simpleflax/blocks/BlockFlax.java#L131

Seems like an odd line - first checking a property on the block (assuming it to be a flax block) before checking whether it is a flax block in the first place.

Not really sure if I'll be able to fix this since I don't have a workspace set up & haven't had time to touch mods in a long time. But if someone wants to submit a PR / etc I'd be happy to merge it and push out a new version
